esphome:
  name: vermilinks-esp32
  friendly_name: VermiLinks ESP32

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: "Knights_IOT"
  password: "smbcr-5540"
  fast_connect: true
  power_save_mode: none
  ap:
    ssid: "VermiLinks_Fallback"
    password: "12345678"

captive_portal:

api:

ota:
  platform: esphome
  password: "Bean2bin2025"

logger:
  level: DEBUG

light:
  - platform: status_led
    id: status_light
    pin: 2

binary_sensor:
  - platform: gpio
    id: vermilinks_esp32_float_sensor
    name: "VermiLinks ESP32 Float Sensor"
    pin:
      number: 16
      mode: INPUT_PULLUP
    device_class: safety

switch:
  - platform: gpio
    id: vermilinks_esp32_water_pump
    name: "VermiLinks ESP32 Water Pump"
    pin: 5
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: vermilinks_esp32_solenoid_valve_1
    name: "VermiLinks ESP32 Solenoid Valve 1"
    pin: 25
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: vermilinks_esp32_solenoid_valve_2
    name: "VermiLinks ESP32 Solenoid Valve 2"
    pin: 26
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: vermilinks_esp32_solenoid_valve_3
    name: "VermiLinks ESP32 Solenoid Valve 3"
    pin: 27
    restore_mode: ALWAYS_OFF

  - platform: template
    id: vermilinks_auto_mode
    name: "VermiLinks AUTO Mode"
    optimistic: true

  - platform: template
    id: vermilinks_manual_mode
    name: "VermiLinks MANUAL Mode"
    optimistic: true

  - platform: template
    id: vermilinks_float_test_mode
    name: "VermiLinks Float Test Mode"
    optimistic: true

  - platform: template
    id: vermilinks_debug_mode
    name: "VermiLinks Debug Mode"
    optimistic: true

sensor:
  - platform: dht
    pin: 4
    model: DHT22
    temperature:
      name: "VermiLinks ESP32 Temperature"
    humidity:
      name: "VermiLinks ESP32 Humidity"
    update_interval: 10s

  - platform: adc
    pin: 34
    name: "VermiLinks ESP32 Soil Moisture (ADC)"
    attenuation: 12db
    update_interval: 10s
    filters:
      - lambda: return (1.0 - x) * 100.0;
