esphome:
  name: vermilinks-esp32
  friendly_name: VermiLinks ESP32

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: "Knights_IOT"
  password: "smbcr-5540"
  fast_connect: true
  power_save_mode: none
  ap:
    ssid: "VermiLinks_Fallback"
    password: "12345678"

captive_portal:

api:

ota:
  platform: esphome
  password: "Bean2bin2025"

logger:
  level: DEBUG

# =====================================================
# STATUS LED (GPIO2)
# =====================================================
light:
  - platform: status_led
    id: status_light
    pin: 2

# =====================================================
# FLOAT SENSOR (GPIO16)
# =====================================================
binary_sensor:
  - platform: gpio
    id: vermilinks_esp32_float_sensor
    name: "VermiLinks ESP32 Float Sensor"
    pin:
      number: 16
      mode: INPUT_PULLUP
    device_class: safety

# =====================================================
# RELAYS + MODES
# =====================================================
switch:
  - platform: gpio
    id: vermilinks_esp32_water_pump
    name: "VermiLinks ESP32 Water Pump"
    pin: 5
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: vermilinks_esp32_solenoid_valve_1
    name: "VermiLinks ESP32 Solenoid Valve 1"
    pin: 25
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: vermilinks_esp32_solenoid_valve_2
    name: "VermiLinks ESP32 Solenoid Valve 2"
    pin: 26
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: vermilinks_esp32_solenoid_valve_3
    name: "VermiLinks ESP32 Solenoid Valve 3"
    pin: 27
    restore_mode: ALWAYS_OFF

  - platform: template
    id: vermilinks_auto_mode
    name: "VermiLinks AUTO Mode"
    optimistic: true

  - platform: template
    id: vermilinks_manual_mode
    name: "VermiLinks MANUAL Mode"
    optimistic: true

  - platform: template
    id: vermilinks_float_test_mode
    name: "VermiLinks Float Test Mode"
    optimistic: true

  - platform: template
    id: vermilinks_debug_mode
    name: "VermiLinks Debug Mode"
    optimistic: true

# =====================================================
# UART (RS485) + MODBUS CONTROLLER
# =====================================================
uart:
  id: rs485_uart
  tx_pin: 18
  rx_pin: 17
  baud_rate: 9600
  stop_bits: 1

modbus:
  id: modbus1
  uart_id: rs485_uart
  flow_control_pin: 23
  send_wait_time: 200ms

modbus_controller:
  - id: soil_modbus
    address: 1
    modbus_id: modbus1
    update_interval: 5s
    command_throttle: 200ms
    max_cmd_retries: 4
    offline_skip_updates: 0
    allow_duplicate_commands: false

# =====================================================
# ALL SENSORS (DHT, ADC, RS485)
# =====================================================
sensor:
  - platform: dht
    pin: 4
    model: DHT22
    temperature:
      name: "VermiLinks ESP32 Temperature"
    humidity:
      name: "VermiLinks ESP32 Humidity"
    update_interval: 10s

  - platform: adc
    pin: 34
    name: "VermiLinks ESP32 Soil Moisture (ADC)"
    attenuation: 12db
    update_interval: 10s
    filters:
      - lambda: return (1.0 - x) * 100.0;

  - platform: modbus_controller
    modbus_controller_id: soil_modbus
    id: rs485_moisture
    name: "RS485 Soil Moisture"
    register_type: holding
    address: 0
    value_type: U_WORD
    unit_of_measurement: "%"
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: soil_modbus
    id: rs485_temperature
    name: "RS485 Soil Temperature"
    register_type: holding
    address: 1
    value_type: U_WORD
    unit_of_measurement: "°C"
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: soil_modbus
    id: rs485_ec
    name: "RS485 Soil EC"
    register_type: holding
    address: 2
    value_type: U_WORD
    unit_of_measurement: "ms/cm"

  - platform: modbus_controller
    modbus_controller_id: soil_modbus
    id: rs485_ph
    name: "RS485 Soil pH"
    register_type: holding
    address: 3
    value_type: U_WORD
    unit_of_measurement: "pH"
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: soil_modbus
    id: rs485_n
    name: "RS485 Nitrogen (N)"
    register_type: holding
    address: 4
    value_type: U_WORD
    unit_of_measurement: "mg/kg"

  - platform: modbus_controller
    modbus_controller_id: soil_modbus
    id: rs485_p
    name: "RS485 Phosphorus (P)"
    register_type: holding
    address: 5
    value_type: U_WORD
    unit_of_measurement: "mg/kg"

  - platform: modbus_controller
    modbus_controller_id: soil_modbus
    id: rs485_k
    name: "RS485 Potassium (K)"
    register_type: holding
    address: 6
    value_type: U_WORD
    unit_of_measurement: "mg/kg"
